dataset:
    # general paths
    csv_path: '.\imagenette\noisy_imagenette.csv'
    data_path: '.\imagenette'
    noisy_labels_x: 'noisy_labels_0'
    moco_classifier_frac: 0.7   # moco dataset part over classifier part for training
    test_frac: 0.3

transform_augmentation: 
    ColorJitter:
        brightness: 0.5
        contrast: 0.5
        saturation: 0.5
        hue: 0.5
    GaussianBlur:
        kernel_size: 1
        sigma_start: 0.1
        sigma_end: 2.0

    p_apply: 0.75

    RandomHorizontalFlip: 0.75
    RandomGrayscale: 0.75
    SizeCrop: 224

dataloader:
    batch_size: 45
    num_workers: 5

moco_model:
    num_epochs: 1000
    val_step: 1
    save_every: 5
    log_path: '.\logs_moco'
    resume_run: 1
    num_classes: 10
    temperature: 0.07
    momentum: 0.99999
    feat_dim: 128
    K: 512  # queue len
    optim:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.00005
