dataset:
    # General Paths
    csv_path: '.\imagenette\noisy_imagenette.csv'
    data_path: '.\imagenette'
    noisy_labels_x: 'noisy_labels_0'
    moco_classifier_frac: 0.5   # moco dataset part over classifier part for training
    test_frac: 0.2

transform_augmentation: 
    ColorJitter:
        brightness: 0.3
        contrast: 0.3
        saturation: 0.3
        hue: 0.3
    GaussianBlur:
        kernel_size: 3
        sigma_start: 0.1
        sigma_end: 1.0

    p_apply: 0.5

    RandomHorizontalFlip: 0.5
    RandomGrayscale: 0.5
    SizeCrop: 200

dataloader:
    batch_size: 256
    num_workers: 4

moco_model:
    num_epochs: 500
    val_step: 10
    save_every: 10
    log_path: '.\logs_moco'
    resume_run: 0
    num_classes: 10
    temperature: 0.07
    momentum: 0.999
    feat_dim: 32
    K: 4096  # queue len
    optim:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0001
