dataset:
    # general paths
    csv_path: '.\imagenette\noisy_imagenette.csv'
    data_path: '..\..\data\imagenette2\imagenette2'
    noisy_labels_x: 'noisy_labels_0'
    moco_classifier_frac: 0.7   # moco dataset part over classifier part for training
    test_frac: 0.3

transform_augmentation: 
    ColorJitter:
        brightness: 0.5
        contrast: 0.5
        saturation: 0.5
        hue: 0.5
    GaussianBlur:
        kernel_size: 1
        sigma_start: 0.1
        sigma_end: 2.0

    p_apply: 0.75

    RandomHorizontalFlip: 0.75
    RandomGrayscale: 0.75
    SizeCrop: 224

dataloader:
    batch_size: 256
    num_workers: 5

moco_model:
    num_classes: 10
    queue_len: 16384
    temprature: 0.07
    momentum: 0.99999

