dataset:
    # General Paths
    csv_path: '.\imagenette\noisy_imagenette.csv'
    data_path: '.\imagenette'
    noisy_labels_x: 'noisy_labels_0'
    moco_classifier_frac: 0.7   # moco dataset part over classifier part for training
    test_frac: 0.0

transform_augmentation: 
    ColorJitter:
        brightness: 0.25
        contrast: 0.25
        saturation: 0.25
        hue: 0.1
    GaussianBlur:
        kernel_size: 3
        sigma_start: 0.1
        sigma_end: 1.0

    p_apply: 0.5

    RandomHorizontalFlip: 0.5
    RandomGrayscale: 0.25
    SizeCrop: 128

dataloader:
    batch_size: 128
    num_workers: 8

moco_model:
    num_epochs: 1000
    val_step: 10
    save_every: 10
    log_path: '.\logs_moco'
    resume_run: 0
    num_classes: 10
    temperature: 0.07
    momentum: 0.999
    feat_dim: 128
    K: 2048  # queue len
    optim:
        lr: 0.05
        momentum: 0.9
        weight_decay: 0.0001

lin_cls:
    num_epochs: 100
    batch_size: 256
    val_step: 5
    save_every: 5
    resume_run: 0
    log_path: '.\logs_lincls'
    optim:
        lr: 0.01
        weight_decay: 0.0001
