name: deep_advanced_topics
dependencies:
    - pytorch
    - pandas
    - seaborn
    - scikit-learn
    - numpy
    - matplotlib
    - scipy
    
 # conda install pytorch torchvision torchaudio cpuonly -c pytorch
